"""PDF report generation for quiz results."""
from __future__ import annotations

from datetime import datetime

from fpdf import FPDF


def _safe_int(value, default: int = 0) -> int:
    """Safely convert a value to int, handling strings, None, etc."""
    if value is None:
        return default
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _safe_float(value, default: float = 0.0) -> float:
    """Safely convert a value to float, handling strings, None, etc."""
    if value is None:
        return default
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


class QuizReportPDF(FPDF):
    """Custom PDF class for quiz result reports."""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, "MCQ Mentor", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(127, 140, 141)
        self.cell(0, 6, "Quiz Result Report", new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(4)
        self.set_draw_color(52, 152, 219)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(127, 140, 141)
        self.cell(0, 10, f"Generated by MCQ Mentor  |  Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(52, 152, 219)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 80, self.get_y())
        self.ln(4)

    def info_row(self, label: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(44, 62, 80)
        self.cell(55, 7, label + ":", new_x="END")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(60, 60, 60)
        self.cell(0, 7, value, new_x="LMARGIN", new_y="NEXT")

    def stat_box(self, label: str, value: str, color: tuple[int, int, int] = (44, 62, 80)):
        self.set_fill_color(245, 246, 250)
        self.set_draw_color(220, 220, 220)
        x = self.get_x()
        y = self.get_y()
        self.rect(x, y, 42, 18, style="DF")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*color)
        self.set_xy(x, y + 2)
        self.cell(42, 8, value, align="C")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(100, 100, 100)
        self.set_xy(x, y + 10)
        self.cell(42, 6, label, align="C")
        self.set_xy(x + 44, y)

    def question_block(
        self,
        num: int,
        question_text: str,
        options: list[dict],
        selected: str | None,
        correct: str | None,
        is_correct: bool | None,
        explanation: str | None,
    ):
        # Check if we need a new page (estimate ~40mm per question)
        if self.get_y() > 240:
            self.add_page()

        # Question header with status badge
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(44, 62, 80)
        status_text = "Not graded"
        status_color = (127, 140, 141)
        if is_correct is True:
            status_text = "Correct"
            status_color = (39, 174, 96)
        elif is_correct is False:
            status_text = "Wrong"
            status_color = (231, 76, 60)
        elif selected is None and correct is not None:
            status_text = "Unanswered"
            status_color = (243, 156, 18)

        self.cell(0, 7, f"{num}. {question_text[:120]}{'...' if len(question_text) > 120 else ''}", new_x="LMARGIN", new_y="NEXT")

        # Status badge
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*status_color)
        self.cell(0, 5, f"   [{status_text}]", new_x="LMARGIN", new_y="NEXT")

        # Options
        self.set_font("Helvetica", "", 9)
        for opt in options:
            key = opt.get("key", "")
            text = opt.get("text", "")
            is_user = selected and key.upper() == selected.upper()
            is_ans = correct and key.upper() == correct.upper()

            prefix = "   "
            if is_user and is_ans:
                self.set_text_color(39, 174, 96)
                prefix = " * "
            elif is_user:
                self.set_text_color(231, 76, 60)
                prefix = " > "
            elif is_ans:
                self.set_text_color(39, 174, 96)
                prefix = " + "
            else:
                self.set_text_color(100, 100, 100)

            display_text = f"{prefix}{key}. {text}"
            if len(display_text) > 90:
                display_text = display_text[:87] + "..."
            self.cell(0, 5, display_text, new_x="LMARGIN", new_y="NEXT")

        # Correct answer and explanation
        self.set_font("Helvetica", "", 9)
        if correct:
            self.set_text_color(39, 174, 96)
            self.cell(0, 5, f"   Correct answer: {correct}", new_x="LMARGIN", new_y="NEXT")
        else:
            self.set_text_color(127, 140, 141)
            self.cell(0, 5, "   No answer key available", new_x="LMARGIN", new_y="NEXT")

        if explanation:
            self.set_text_color(100, 100, 100)
            expl_display = f"   Explanation: {explanation}"
            if len(expl_display) > 150:
                expl_display = expl_display[:147] + "..."
            self.cell(0, 5, expl_display, new_x="LMARGIN", new_y="NEXT")

        self.ln(3)

    def mistake_block(
        self,
        num: int,
        question_text: str,
        selected: str | None,
        correct: str | None,
        explanation: str | None,
        mastery_status: str | None,
    ):
        if self.get_y() > 245:
            self.add_page()

        self.set_font("Helvetica", "B", 10)
        self.set_text_color(231, 76, 60)
        q_display = f"{num}. {question_text[:110]}{'...' if len(question_text) > 110 else ''}"
        self.cell(0, 7, q_display, new_x="LMARGIN", new_y="NEXT")

        self.set_font("Helvetica", "", 9)
        self.set_text_color(231, 76, 60)
        self.cell(0, 5, f"   Your answer: {selected or 'N/A'}", new_x="LMARGIN", new_y="NEXT")

        self.set_text_color(39, 174, 96)
        self.cell(0, 5, f"   Correct answer: {correct or 'N/A'}", new_x="LMARGIN", new_y="NEXT")

        if explanation:
            self.set_text_color(100, 100, 100)
            expl_display = f"   Explanation: {explanation}"
            if len(expl_display) > 150:
                expl_display = expl_display[:147] + "..."
            self.cell(0, 5, expl_display, new_x="LMARGIN", new_y="NEXT")

        if mastery_status:
            self.set_text_color(52, 152, 219)
            self.cell(0, 5, f"   Mastery: {mastery_status.replace('_', ' ').title()}", new_x="LMARGIN", new_y="NEXT")

        self.ln(2)


def generate_quiz_report(
    result: dict,
    question_set: dict | None,
    material: dict | None,
    user_email: str | None,
    mistakes: list[dict] | None = None,
) -> bytes:
    """Generate a PDF report for a quiz attempt.

    Args:
        result: QuizResult dict with questions, scores, etc.
        question_set: The question set metadata (title, etc.)
        material: The learning material metadata (title, etc.)
        user_email: The user's email address
        mistakes: Optional list of mistake bank entries for this attempt

    Returns:
        PDF file content as bytes
    """
    import logging
    _log = logging.getLogger(__name__)

    # Debug: log types of numeric fields
    for key in ("total_questions", "correct", "incorrect", "unanswered", "percentage", "time_spent_seconds"):
        val = result.get(key)
        _log.debug("generate_quiz_report: result[%r] = %r (type=%s)", key, val, type(val).__name__ if val is not None else "NoneType")

    pdf = QuizReportPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # --- Header Info ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 8, "Result Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.info_row("Student", user_email or "N/A")
    pdf.info_row("Material", material.get("title", "N/A") if material else "N/A")
    pdf.info_row("Quiz Set", question_set.get("title", "N/A") if question_set else "N/A")

    mode = result.get("mode", "practice")
    mode_label = {
        "practice": "Saved Material Practice",
        "exam": "Exam Mode",
        "mistakes": "Mistake Practice",
    }.get(mode, mode)
    pdf.info_row("Mode", mode_label)

    submitted = result.get("submitted_at")
    if submitted:
        try:
            if isinstance(submitted, datetime):
                dt = submitted
            else:
                dt = datetime.fromisoformat(str(submitted).replace("Z", "+00:00"))
            pdf.info_row("Date & Time", dt.strftime("%B %d, %Y at %I:%M %p"))
        except (ValueError, AttributeError, TypeError):
            pdf.info_row("Date & Time", str(submitted))
    else:
        pdf.info_row("Date & Time", "N/A")

    time_spent = _safe_int(result.get("time_spent_seconds"))
    if time_spent:
        m, s = divmod(time_spent, 60)
        pdf.info_row("Time Spent", f"{m}m {s}s" if m else f"{s}s")

    # Check if auto-grading was available
    questions_data = result.get("questions", [])
    # Check via is_correct - if any question has a definitive True/False, grading was done
    grading_available = any(
        q.get("is_correct") is not None
        for q in questions_data
        if isinstance(q, dict)
    )
    pdf.info_row("Auto-Graded", "Yes" if grading_available else "No")
    if not grading_available:
        pdf.ln(2)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(243, 156, 18)
        pdf.cell(
            0,
            5,
            "Auto-grading was not available because no answer key was provided.",
            new_x="LMARGIN",
            new_y="NEXT",
        )

    pdf.ln(6)

    # --- Score Summary ---
    pdf.section_title("Score Summary")

    total = _safe_int(result.get("total_questions"))
    correct = _safe_int(result.get("correct"))
    incorrect = _safe_int(result.get("incorrect"))
    unanswered = _safe_int(result.get("unanswered"))
    percentage = _safe_float(result.get("percentage"))

    # Stat boxes in a row
    pdf.stat_box("Total", str(total))
    pdf.stat_box("Correct", str(correct), (39, 174, 96))
    pdf.stat_box("Wrong", str(incorrect), (231, 76, 60))
    pdf.stat_box("Skipped", str(unanswered), (243, 156, 18))
    pdf.ln(22)

    # Percentage bar
    pdf.set_font("Helvetica", "B", 20)
    pct_color = (39, 174, 96) if percentage >= 70 else (243, 156, 18) if percentage >= 40 else (231, 76, 60)
    pdf.set_text_color(*pct_color)
    pdf.cell(0, 12, f"{percentage}%", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"{correct} out of {total} correct", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(6)

    # --- Question Review ---
    pdf.section_title("Question Review")

    for i, q_data in enumerate(questions_data):
        if not isinstance(q_data, dict):
            continue

        question = q_data.get("question", {})
        if not isinstance(question, dict):
            continue

        options = question.get("options", [])
        if not isinstance(options, list):
            options = []

        pdf.question_block(
            num=i + 1,
            question_text=question.get("question_text", "N/A"),
            options=options,
            selected=q_data.get("selected_answer"),
            correct=question.get("correct_answer"),
            is_correct=q_data.get("is_correct"),
            explanation=question.get("explanation"),
        )

    # --- Mistake Summary ---
    if mistakes:
        pdf.add_page()
        pdf.section_title("Mistake Summary")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(0, 7, f"Total mistakes: {len(mistakes)}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        for i, m in enumerate(mistakes):
            question = m.get("question", {})
            if not isinstance(question, dict):
                continue

            pdf.mistake_block(
                num=i + 1,
                question_text=question.get("question_text", "N/A"),
                selected=m.get("selected_answer"),
                correct=question.get("correct_answer"),
                explanation=question.get("explanation"),
                mastery_status=m.get("mastery_status"),
            )

    return bytes(pdf.output())
